# Generated by Django 5.2.4 on 2025-07-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'verbose_name': 'Admin'},
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'verbose_name': 'Doctor'},
        ),
        migrations.AlterModelOptions(
            name='receptionist',
            options={'verbose_name': 'Receptionist'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Main UserProfile'},
        ),
        migrations.AddField(
            model_name='patient',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
