# Generated by Django 5.2.4 on 2025-07-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0002_alter_admin_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_name_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='department',
            name='department_name_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_title_en',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobtitle',
            name='job_title_ru',
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='type_en',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='servicetype',
            name='type_ru',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
