# Generated by Django 5.2.4 on 2025-07-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0003_department_department_name_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=16),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_status',
            field=models.CharField(choices=[('pre-registration', 'Pre-registration'), ('waiting', 'Waiting'), ('had an appointment', 'Had an appointment'), ('canceled', 'Canceled')], max_length=32),
        ),
        migrations.AlterField(
            model_name='patient',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Card')], max_length=32),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor')], max_length=32),
        ),
    ]
