# Generated by Django 5.2.4 on 2025-07-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0004_alter_patient_gender_alter_patient_patient_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='primary_patient',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
