# Generated by Django 5.2.4 on 2025-07-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0005_patient_primary_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='role',
        ),
        migrations.AddField(
            model_name='admin',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor')], default='admin', max_length=16),
        ),
        migrations.AddField(
            model_name='doctor',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor')], default='doctor', max_length=16),
        ),
        migrations.AddField(
            model_name='receptionist',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor')], default='receptionist', max_length=16),
        ),
    ]
