# Generated by Django 5.2.4 on 2025-07-28 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0006_remove_userprofile_role_admin_role_doctor_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_med.room'),
        ),
    ]
