# Generated by Django 5.2.4 on 2025-08-01 06:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0008_alter_patient_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='bonus',
            field=models.PositiveSmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(60)]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_patients', to='crm_med.doctor'),
        ),
    ]
