# Generated by Django 5.2.4 on 2025-08-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0009_alter_doctor_bonus_alter_patient_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_role',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('doctor', 'Doctor')], max_length=32, null=True),
        ),
    ]
