# Generated by Django 5.2.4 on 2025-08-08 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm_med', '0010_userprofile_user_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ('-appointment_date',)},
        ),
        migrations.RemoveField(
            model_name='admin',
            name='role',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='role',
        ),
        migrations.RemoveField(
            model_name='receptionist',
            name='role',
        ),
    ]
